services:
  bff:
    container_name: bff-app
    hostname: bff.example.com
    build:
      context: ./bff-app/
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
      - "8443:8443"

  svc:
    container_name: svc-app
    hostname: svc.example.com
    build:
      context: ./svc-app/
      dockerfile: ./Dockerfile
    ports:
      - "8081:8080"
      - "8444:8443"

  rk:
    container_name: rk-app
    hostname: rk.com
    build:
      context: ./rk-app/
      dockerfile: ./Dockerfile
    ports:
      - "8082:8080"
      - "8445:8443"
